### ISSUE TITLE
Errors when parsing HTML

### ISSUE THREAD

**Issue by aharth** [ldodds/bricklink#1]
I got 
   $ rake download
to work, but
   $ rake convert
outputs a lot of errors:
    Fatal error: xmlParseEntityRef: no name at :8.
or:
    Fatal error: Premature end of data in tag HTML line 2 at :533.

The result is a file inventories.nt, but all other files in /data/nt are empty.

Any idea what to try?

**Comment by aharth** [comment]
The underlying problem was a change in RDF.rb, see https://twitter.com/danbri/status/723568919211069440

**Comment by ldodds** [comment]
Glad you resolved this. However unless you want this data for personal use I wouldn't use the code.

Originally I had permission from the previous maintainers of bricklink that the catalog data could be republished as open data. However they've since changed their terms of use which means you can't redistribute it.

There are other sources for similar data, e.g. Brickset, Rebrickable.
